### ISSUE TITLE
Table with raw data?

### ISSUE THREAD

**Issue by nfoen** [tombenner/reports_kit#24]
This is a great project.

It is perfect for the graphs that we need to display, but I was wondering if there is any way to render a table with raw or custom data? Something like this:

ID | Author | Date | Category
--- | --- | --- | ---
1 | Jane | 2017-12-05 | Question
2 | John | 2017-12-10 | Bug
3 | Jean | 2017-12-12 | Feature

**Comment by kirantpatil** [comment]
This may help you, https://www.reportskit.co/subcategories/tables.

**Comment by nfoen** [comment]
Hi @kirantpatil - These tables are great when we have up to 2 dimensions, and we want to display the count/aggregates for each combination. I would like to display a subset of the data, the equivalent to a sql query without a group by statement, like:
`select posts.id, author.name, posts.created_at, posts.date, posts.category from posts join authors on posts.author_id = authors.id`

Can we support that with the existing functionality?

**Comment by kirantpatil** [comment]
Sorry, I don't know. Were you able to find the solution ?

**Comment by tombenner** [comment]
ReportsKit currently only supports showing data generated using aggregate functions (e.g. COUNT, SUM, etc) and not arbitrary SQL queries, so this use case unfortunately isn't currently supported. I am thinking about strategies for supporting arbitrary SQL queries (instead of requiring YAML configuration), though, so this may be supported in the future.
