### ISSUE TITLE
[FAQ] Color coding Table rows

### ISSUE THREAD

**Issue by kirantpatil** [tombenner/reports_kit#4]
Hi,

I would like to color code the [Table](https://www.reportskit.co/subcategories/tables) rows with red, green and blue based on table column cell value as below.

Please guide us on how to achieve this ?

For example,

```
def row_class(issue)
    case issue.status
    when "fixed" then "green"
    when "rejected" then "red"
    else "blue"
    end
  end

```
Thanks.

**Comment by tombenner** [comment]
This isn't currently supported. If you'd like to add support for it in a generalized way, feel free to do so. The code that generates the tables is [here](https://github.com/tombenner/reports_kit/blob/master/app/assets/javascripts/reports_kit/lib/table.js).

Because it's unclear how important this issue is, I'm going to close it to avoid having a huge backlog of open, unimportant issues. If there's more interest in this, we can reopen it.

**Comment by kirantpatil** [comment]
@tombenner thanks for your feedback.

My usecase is Bus occupancy report, below is the png file.

I would like to color code the row based on the occupancy in %.



![occupancy report](https://user-images.githubusercontent.com/1178055/31610195-b1def82e-b266-11e7-82e9-e23d10167022.png)

**Comment by kirantpatil** [comment]
Is it possible to create new operator to get % as below ?

`(%) Occupancy = (occupied_seats * 100) / total_seats`
