### ISSUE TITLE
[FAQ] reports_kit vs active_reporting vs datagrid

### ISSUE THREAD

**Issue by kirantpatil** [tombenner/reports_kit#5]
Hi,

I am now confused with 3 [implementation(reports_kit](https://github.com/tombenner/reports_kit) vs [active_reporting](https://github.com/t27duck/active_reporting) vs [datagrid)](https://github.com/bogdan/datagrid) Reporting module in Rails.

Please compare and throw some light on merit and demerits of each.

Thanks.

**Comment by tombenner** [comment]
One way to do this comparison would be to make a feature matrix comparing these libraries. If anyone would like to make one, we could add it to the [ReportsKit docs](https://github.com/tombenner/reports_kit_docs). I don't have time to do this now, but if anyone else would like to, feel free to do so.

In the meantime, I'm hesitant to make broad generalizations about these three libraries without more thorough research. There are some significant differences that should be apparent by looking at the documentation of each library, though. Because it's unclear how important this issue is, I'm going to close it to avoid having a huge backlog of open, unimportant issues. If there's more interest in this, we can reopen it.
