### ISSUE TITLE
Invalid SQL when aggregating over single non-date column

### ISSUE THREAD

**Issue by pascalbetz** [tombenner/reports_kit#6]
Playing with reports_kit after reading about it in 'Ruby Weekly' i struggled with a simple report.

Rails: 5.1.4
Postgres: 9.6
reports_kit: 0.3.2
Model: `Device` with string column `role`

No special configuration in the model

Following report

```
measure: device
dimensions:
- role
```
Creates an invalid SQL statement:

`SELECT  COUNT(DISTINCT *) AS count_all, "devices"."role" AS devices_role FROM "devices" GROUP BY "devices"."role" ORDER BY 1 DESC LIMIT $1)`

(the `COUNT(DISTINCT *)` part is invalid for postgres)

The single aggregation works for Date-Fields (like created_at, updated_at) but not for others. Aggregation over multiple columns seem to work, no matter what type.

Not entirely sure (=> not at all) how reports_kit work but following helped:

* adding a `relation.select(...)` at https://github.com/tombenner/reports_kit/blob/master/lib/reports_kit/reports/data/aggregate_one_dimension.rb#L25

Please let me know if I'm doing something wrong or if this is realy a bug and I can provide a fix.

**Comment by tombenner** [comment]
Interesting; this is indeed a bug, but it looks like it's due to an incompatibility with some modification (in ActiveRecord, I'm assuming) that occurred between Rails `5.1.0` and `5.1.4`. The [documentation's app](https://github.com/tombenner/reports_kit_docs) is currently on `5.1.0` using Postgres, but I upgraded it to `5.1.4` locally and was able to repro the described issue.

If I replace `:count` with `[:count, :id]` [here](https://github.com/tombenner/reports_kit/blob/master/lib/reports_kit/reports/series.rb#L48), then the query is constructed correctly. This is a significant issue, and I'd like to fix it soon. I'd like to better understand the issue before making a change, and I have limited time this morning, but I should have time this evening/weekend. If you'd like to investigate further independently, definitely feel free to!

**Comment by pascalbetz** [comment]
Quick update: 

Works with: 5.1.0, 5.1.1, 5.1.2, 5.1.3
Fails with: 5.1.4

So I'd say problem was introduced just with 5.1.4 and indeed there is a change mentioned in the README related to _COUNT DISTINCT_ (https://github.com/rails/rails/blob/v5.1.4/activerecord/CHANGELOG.md).

I'll dig deeper in an hour or two, perhaps I can find what causes the problem.

**Comment by pascalbetz** [comment]
Pointed it down to some piece of code in AR (see linked Rails issue). 

I think adding the column as argument to `count` would fix it for both versions:

`MyModel.group(:id).order(id: :asc).limit(30).distinct.count(:id)`

This works in 5.1.4 and 5.1.3

**Comment by pascalbetz** [comment]
Problem has been fixed in Rails by https://github.com/rails/rails/commit/87ca68e76eec68ec61fc0d3d3bf315b4bfe45c42

I assume this will be out in next patch release.

**Comment by tombenner** [comment]
@pascalbetz Many thanks for the thorough investigation! And I'm glad you surfaced this bug to the Rails team.

As described above, I've add the primary key as an argument to `count` in [f0796886](https://github.com/tombenner/reports_kit/commit/f0796886#diff-4fe5e53cbb1445ecb3d9fbe1225ccc22). This commit also adds significant test coverage by testing ReportsKit against [additional versions of Rails](https://github.com/tombenner/reports_kit/commit/f0796886#diff-3bb7346aca79d8142e16e61372bd04dc).

This fix is available in ReportsKit 0.3.3, which I just pushed out.

**Comment by pascalbetz** [comment]
Nice 👏
